defaults:
  - model: ae/ae
  - dataset: ibd
  - test: features_addition
  - machine: gpu
  - _self_
  - shared_config

task_name: "base ae task"

seed: 1
fast_dev_run: false

dataset:
  oversample: false

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local