defaults:
  - model: ae/ae
  - dataset: ibd
  - machine: gpu
  - _self_
  - shared_config

task_name: "base ae task"

seed: 1
fast_dev_run: false

dataset:
  oversample: false

bias: true
bias_type: "exclusion"
# exclusion distortion

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local