defaults:
  - _self_
  - test: ../met_test/features_removal
  - standard_task_id: ../past_tasks/tasks/standard
  - test_task_id: ../past_tasks/tasks/features_removal

task_name: 'pipeline aggregator'

execution_type: "draft"


# standard_task_id:
#   ae: 01c83ec033504b45b5464f3eeccfe4fc
#   clf: 2c67b88abdf4403996243083ca9583cb
# test_task_id:
#   ae: 17722dff87794e04ab5ba86a516d43cb
#   clf: 95a499fbb1494bb48372bb0d1b992eec

# execution_type: "local"

dataset: ibd