defaults:
  - test: ../met_test/features_addition

task_name: 'pipeline aggregator'

standard_task_id:
  ae: ""
  clf: ""
test_task_id:
  ae: ""
  clf: ""
execution_type: "draft"


# standard_task_id:
#   ae: "524e8abc9a04470fa88b41e9a7708905"
#   clf: "375688850d07434d80c024bfb5bf4b7e"
# test_task_id:
#   ae: "c579ae60402e44dda527d067cc14fc34"
#   clf: "e45efa46c9e249f58354af912b21027f"
# execution_type: "local"

dataset: ibd