defaults:
  - _self_
  - clf_model: shallow
  - dataset: ibd
  - machine: gpu

task_name: "base clf task"

seed: 1234

test: true
train: true
fast_dev_run: false

bias: false

dataset:
  oversample: true

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local