defaults:
  - model: clf/mlp
  - dataset: ibd
  - machine: gpu
  - _self_
  - shared_config

task_name: "base clf task"

ae_task_id: ""

seed: 1234
fast_dev_run: false

dataset:
  oversample: true

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local
