defaults:
  - model: clf/mlp
  - dataset: ibd
  - test: ../met_test/features_addition
  - machine: gpu
  - _self_
  - shared_config

task_name: "base clf task"

ae_task_id: ""

seed: 1
fast_dev_run: false

dataset:
  oversample: false

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local
