defaults:
  - _self_
  - ae_model: ae
  - clf_model: shallow
  - dataset: ibd
  - machine: gpu
  - logs: prostate

task_name: "base task"

seed: 1234

test: true
train: true
fast_dev_run: false

bias: true
bias_type: "exclusion"
# exclusion distortion

dataset:
  oversample: true

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local