defaults:
  - _self_
  - model: ae
  - dataset: cirrhosis
  - machine: gpu
  - logs: prostate

task_name: "base task"

seed: 1234

test: true
train: true
fast_dev_run: false

bias: true
bias_type: "exclusion"
# exclusion distortion

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8