defaults:
  - ae_model: ae
  - clf_model: shallow
  - dataset: ibd
  - machine: gpu
  - _self_

task_name: "base task"

seed: 1234
fast_dev_run: false

dataset:
  oversample: true

bias: true
bias_type: "exclusion"
# exclusion distortion

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8
  execution_type: "draft"
  # draft remote local