defaults:
  - _self_
  - model: ae
  - dataset: prostate
  - machine: gpu
  - logs: prostate

task_name: "Base task"

seed: 1234

test: true
train: true
fast_dev_run: true

cross_validation:
  folds: 10

machine:
  workers: 8