defaults:
  - _self_
  - model: ae
  - dataset: ibd
  - machine: gpu
  - logs: prostate

task_name: "training base task"

seed: 1234

test: true
train: true
fast_dev_run: false

cross_validation:
  flag: false
  folds: 10

machine:
  workers: 8