defaults:
  - _self_
  - dataset: ibd
  - past_tasks: pipeline_none
  - test: ../met_test/features_addition
  - no_test: ../met_test/none

ae_base_task_name: "base ae task"
clf_base_task_name: "base clf task"
aggregator_task_name: "pipeline aggregator"

seed: 1234

machine:
  gpus_index: [1, 2]
