defaults:
  - _self_
  - dataset: ibd
  - past_tasks: none

ae_base_task_name: "base ae task"
clf_base_task_name: "base clf task"
aggregator_task_name: "pipeline aggregator"

bias_type: "distortion"
# exclusion distortion

past_tasks: 
  use: False
  standard:
    ae: ""
    clf: ""
  biased:
    ae: ""
    clf: ""

machine:
  gpus_index: [2, 2]
