defaults:
  - _self_
  - dataset: ibd
  - past_tasks: none
  - test: met_test/fetures_addition
  - no_test: test/none

ae_base_task_name: "base ae task"
clf_base_task_name: "base clf task"
aggregator_task_name: "pipeline aggregator"

past_tasks: 
  use: False
  standard:
    ae: ""
    clf: ""
  test:
    ae: ""
    clf: ""

machine:
  gpus_index: [2, 2]
